#pragma once

#define APP 44

#define LABEL_MACHINE_ERR_INIT_FAILED										((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|1))
#define LABEL_MACHINE_ERR_HAVE_NOT_INITED									((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|2))
#define LABEL_MACHINE_ERR_TERM_FAILED										((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|3))
#define LABEL_MACHINE_ERR_REINIT											((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|4))
#define LABEL_MACHINE_ERR_NOZZLE_DEFLECTION_OUT_OF_RANGE					((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|5))
#define LABEL_MACHINE_ERR_MOTION_PARS										((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|6))
#define LABEL_MACHINE_ERR_TRAJ_CURVE_X_MAX_JERK_EXCEEDED					((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|7))
#define LABEL_MACHINE_ERR_TRAJ_CURVE_X_MAX_ACCELERATION_EXCEEDED			((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|8))
#define LABEL_MACHINE_ERR_TRAJ_CURVE_X_MAX_VELOCITY_EXCEEDED				((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|9))
#define LABEL_MACHINE_ERR_TRAJ_CURVE_Y_MAX_JERK_EXCEEDED					((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|10))
#define LABEL_MACHINE_ERR_TRAJ_CURVE_Y_MAX_ACCELERATION_EXCEEDED			((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|11))
#define LABEL_MACHINE_ERR_TRAJ_CURVE_Y_MAX_VELOCITY_EXCEEDED				((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|12))
#define LABEL_MACHINE_ERR_TRAJ_MAX_JERK_EXCEEDED							((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|13))
#define LABEL_MACHINE_ERR_TRAJ_MAX_ACCELERATION_EXCEEDED					((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|14))
#define LABEL_MACHINE_ERR_TRAJ_MAX_VELOCITY_EXCEEDED						((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|15))
#define LABEL_MACHINE_ERR_START_POSITION_CHANGED							((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|16))
#define LABEL_MACHINE_ERR_STREAM_TIMEOUT									((NYCE_STATUS)((NYCE_ERROR_MASK)|(APP<<NYCE_SUBSYS_SHIFT)|17))